export const JobsData = [
	{
        name: 'Eniola Lucas',
        role: 'Applicant',
        status: 'upcoming',
        title: 'House Cleaner',
        date: 'Tuesday 3rd March, 2024',
        time:'9:00 AM.',
        duration:'2hrs',
		amount:'5000',
		image: 'profile.png',
		location: '4517 Washington Ave. Manchester, Kentucky 39495, Ilorin Nigeria',
        date_posted: '2 days ago',
        no_of_application: '7'
	},
	{
        name: 'Sanni Lawal',
        role: 'Applicant',
        status: 'ongoing',
        title: 'Professional Grass Cutter',
        date: 'Monday 2nd March, 2024',
        time:'9:00 AM.',
        duration:'2hrs',
		amount:'4000',
		image: 'profile.png',
		location: '4517 Washington Ave. Manchester, Kentucky 39495, Ilorin Nigeria',
        date_posted: '2 days ago',
        no_of_application: '1'
	},
	{
        name: 'Ahmed Musa',
        role: 'Applicant',
        status: 'completed',
        title: 'Laundry Chores',
        date: 'Monday 6th January, 2025',
        time:'9:00 AM.',
        duration:'2hrs',
		amount:'4000',
		image: 'profile.png',
		location: '4517 Washington Ave. Manchester, Kentucky 39495, Ilorin Nigeria',
        date_posted: '2 days ago',
        no_of_application: '3'
	},
	{
        name: 'John Mathew',
        role: 'Applicant',
        status: 'canceled',
        title: 'Professional Painter',
        date: 'Monday 2nd March, 2024',
        time:'9:00 AM.',
        duration:'2hrs',
		amount:'4000',
		image: 'profile.png',
		location: '4517 Washington Ave. Manchester, Kentucky 39495, Ilorin Nigeria',
        date_posted: '2 days ago',
        no_of_application: '2'
	},
]