# Generated by Django 5.1.6 on 2025-03-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="duration",
        ),
        migrations.AddField(
            model_name="job",
            name="shift_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="shift_start",
            field=models.DateTimeField(null=True),
        ),
    ]
