# Generated by Django 5.1.6 on 2025-03-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_remove_job_duration_job_shift_end_job_shift_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="shift_type",
            field=models.CharField(
                choices=[("morning", "Morning"), ("night", "Night")], max_length=20
            ),
        ),
    ]
