# Generated by Django 5.1.6 on 2025-02-25 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_delete_locationhistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="amount",
            new_name="rate",
        ),
        migrations.RemoveField(
            model_name="job",
            name="rate_per_hour",
        ),
    ]
