# Generated by Django 5.1.6 on 2025-03-14 11:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_job_is_active_job_is_online_alter_job_shift_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-applied_at"]},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="rating",
            name="rating_between_1_and_5",
        ),
        migrations.RemoveConstraint(
            model_name="rating",
            name="unique_reviewer_reviewed",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="is_accepted",
            new_name="is_shown_up",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="last_latitude",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="last_longitude",
            new_name="longitude",
        ),
        migrations.RemoveField(
            model_name="job",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_online",
        ),
        migrations.RemoveField(
            model_name="job",
            name="last_address",
        ),
        migrations.RemoveField(
            model_name="job",
            name="shift_end",
        ),
        migrations.RemoveField(
            model_name="job",
            name="shift_start",
        ),
        migrations.AddField(
            model_name="application",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="rating",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("shortlisted", "Shortlisted"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="actual_shift_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="actual_shift_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="applicants_accepted",
            field=models.ManyToManyField(
                blank=True,
                related_name="accepted_jobs",
                through="jobs.Application",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.CharField(default="No description provided", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="recurring_days",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated days (e.g., Monday,Wednesday,Friday)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="service_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="job",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="badges",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="job",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posted_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jobs.jobindustry",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("held", "Held in Escrow"),
                    ("partial", "Partially Paid"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="job",
            name="shift_type",
            field=models.CharField(
                choices=[
                    ("morning", "Morning (6AM - 2PM)"),
                    ("afternoon", "Afternoon (2PM - 8PM)"),
                    ("night", "Night (8PM - 6AM)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="start_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("upcoming", "Upcoming"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jobs.jobsubcategory",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("applicant", "Applicant"),
                    ("client", "Client"),
                    ("admin", "Admin"),
                ],
                default="applicant",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("job", "applicant")},
        ),
        migrations.AlterUniqueTogether(
            name="savedjob",
            unique_together={("user", "job")},
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "payment_status"], name="jobs_job_status_d10cda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["latitude", "longitude"], name="jobs_job_latitud_d115f8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1.0), ("rating__lte", 5.0)),
                name="rating_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("reviewer", "reviewed"), name="unique_rating"
            ),
        ),
    ]
