# Generated by Django 5.1.6 on 2025-02-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_rename_amount_job_rate_remove_job_rate_per_hour"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="time",
            new_name="end_time",
        ),
        migrations.RemoveField(
            model_name="job",
            name="description",
        ),
        migrations.AddField(
            model_name="job",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="applicants_needed",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("single_day", "Single Day"),
                    ("multiple_days", "Multiple Days"),
                ],
                default="single_day",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="shift_type",
            field=models.CharField(
                choices=[("day_shift", "Day Shift"), ("night_shift", "Night Shift")],
                default="day_shift",
                max_length=20,
            ),
        ),
    ]
