# Generated by Django 5.1.6 on 2025-02-26 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_rename_time_job_end_time_remove_job_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="image",
        ),
    ]
