# Generated by Django 5.1.6 on 2025-03-06 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_remove_job_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="applicant",
        ),
        migrations.AddField(
            model_name="job",
            name="applicants",
            field=models.ManyToManyField(
                blank=True, related_name="applied_jobs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
