# Generated by Django 5.1.6 on 2025-03-06 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_remove_job_applicant_job_applicants_job_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="applicants",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="job",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
