# Generated by Django 4.2 on 2025-02-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_rename_livelocation_locationhistory_dispute_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
        migrations.AddField(
            model_name="job",
            name="last_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="last_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="last_location_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="last_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locationhistory",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
