# Generated by Django 4.2 on 2025-02-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_remove_job_location_job_last_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
