# Generated by Django 4.2 on 2025-02-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_job_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
