# Generated by Django 4.2 on 2025-02-18 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0009_profile_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user_type",
            new_name="role",
        ),
    ]
