# Generated by Django 5.1.6 on 2025-02-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_rename_user_type_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("applicant", "Applicant"),
                    ("client", "Client"),
                    ("admin", "Admin"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
