# Generated by Django 5.1.6 on 2025-03-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_alter_savedjob_user_alter_rating_reviewer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.FloatField(default=5.0),
        ),
    ]
