# Generated by Django 5.1.6 on 2025-02-20 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_alter_profile_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="applicants_needed",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of workers needed."
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("single_day", "Single Day"),
                    ("multiple_days", "Multiple Days"),
                ],
                default="single_day",
                help_text="Single day or multiple-day job.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="rate_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Hourly rate for the job.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="shift_type",
            field=models.CharField(
                choices=[("day_shift", "Day Shift"), ("night_shift", "Night Shift")],
                default="day_shift",
                help_text="Day shift or night shift.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional total pay or budget.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Optional URL or path to an image.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.jobindustry",
            ),
        ),
        migrations.CreateModel(
            name="JobSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="jobs.jobindustry",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.jobsubcategory",
            ),
        ),
    ]
