# Generated by Django 5.1.6 on 2025-03-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
