# Generated by Django 5.1.6 on 2025-03-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0012_alter_rating_rating_delete_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="pay_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
