# Generated by Django 5.1.6 on 2025-03-11 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0014_alter_profile_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="feedback",
            new_name="reviews",
        ),
    ]
