# Generated by Django 5.1.6 on 2025-03-11 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0015_rename_feedback_rating_reviews"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="reviews",
            new_name="feedback",
        ),
    ]
