# Generated by Django 5.1.6 on 2025-03-12 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0017_alter_rating_options_alter_rating_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="pay_status",
        ),
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("single_day", "Single Day"),
                    ("multiple_days", "Multiple Days"),
                ],
                default="single_day",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="last_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
