# Generated by Django 5.1.7 on 2025-03-16 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobchat", "0001_initial"),
        ("jobs", "0002_dispute_assigned_admin_dispute_reason_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="message",
            name="jobchat_mes_sender__010fab_idx",
        ),
        migrations.AlterField(
            model_name="message",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="jobs.job",
                verbose_name="Related Job",
            ),
        ),
    ]
