# Generated by Django 5.1.7 on 2025-03-16 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobchat", "0002_remove_message_jobchat_mes_sender__010fab_idx_and_more"),
        ("jobs", "0002_dispute_assigned_admin_dispute_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="jobs.job",
                verbose_name="Job",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender"], name="jobchat_mes_sender__010fab_idx"
            ),
        ),
    ]
