# Generated by Django 5.1.6 on 2025-02-23 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobchat", "0002_locationhistory"),
        ("jobs", "0002_delete_locationhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="locationhistory",
            index=models.Index(
                fields=["user", "latitude", "longitude"],
                name="jobchat_loc_user_id_a36f45_idx",
            ),
        ),
    ]
