# Generated by Django 5.1.7 on 2025-03-16 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobchat", "0003_alter_message_job_and_more"),
        ("jobs", "0002_dispute_assigned_admin_dispute_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationhistory",
            options={},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="locationhistory",
            name="jobchat_loc_timesta_901595_idx",
        ),
        migrations.RemoveIndex(
            model_name="locationhistory",
            name="jobchat_loc_job_id_9b3547_idx",
        ),
        migrations.RemoveIndex(
            model_name="locationhistory",
            name="jobchat_loc_user_id_a36f45_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="jobchat_mes_timesta_7f1286_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="jobchat_mes_job_id_a2efa0_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="jobchat_mes_sender__010fab_idx",
        ),
        migrations.RemoveField(
            model_name="locationhistory",
            name="address",
        ),
        migrations.AlterField(
            model_name="locationhistory",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="jobs.job",
            ),
        ),
        migrations.AlterField(
            model_name="locationhistory",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="locationhistory",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="locationhistory",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="locationhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="jobs.job",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
