# Generated by Django 5.1.7 on 2025-03-22 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobchat", "0005_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
